apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  labels:
    app: flask-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: flask-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: flask-api-deployment
    labels:
        app: flask-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: flask-api
    template:
        metadata:
            labels:
                app: flask-api
        spec:
            containers:
              - name: flask-api
                image: flask-api
                ports:
                  - containerPort: 8080